apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app-prod-rollout
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/aki0000/sample-app-with-argocd.git
    targetRevision: main
    path: kustomize-rollout/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - RespectIgnoreDifferences=true
